### PR TITLE
complete lecture1

### PR DESCRIPTION
**Pull request by ZHDreamer**
### Solutions for Lecture 1

eta reduction

```haskell
lowerAndGreater n list = helper 0 0 list
-- reduce to
lowerAndGreater n      = helper 0 0
```

### CODE REVIEW

**Comment by chshersh** [comment]
Hi @ZHDreamer 👋🏻 

I see that you merged this PR but you still mentioned my username in the PR description.
In that case, would you like to get my feedback on your solutions anyway?

**Comment by ZHDreamer** [comment]
Hi @chshersh , I think it was a mistake. I'm not familiar with operating pull requests.

**Review by chshersh — COMMENTED** [review]
Congrats! The first homework is complete 👏🏼 
Hope you enjoyed the course so far. Keep up the great work, and feel free to ask any questions if you have 👌🏼

<hr>

Don't worry about doing any mistakes with PR's for now 👌🏻 
It should come with practice 🙂 

In any case, I haven't found anything where I can suggest improvements. The solutions are already perfect 🏆 Hope you'll continue with the next lecture! 🥳

**Comment by ZHDreamer** [comment]
Thank you for the feedback! It makes me more confident to continue with the next lecture. 😀

**Pull request merged**
